spring.application.name=money-manager
server.port=8081

# DB cred
spring.datasource.url=jdbc:mysql://localhost:3306/money_manager
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update 
# validate in prod
spring.jpa.show-sql=true
